version: '3.8'

services:
  product-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: modern-product-search-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EXTERNAL_API_BASE_URL=https://dummyjson.com
      - EXTERNAL_API_TIMEOUT_CONNECT=5000
      - EXTERNAL_API_TIMEOUT_READ=10000
      - JAVA_OPTS=-Xmx512m -Xms256m -XX:+UseG1GC
      - LOGGING_LEVEL_COM_PRODUCTAPI=INFO
      - LOGGING_LEVEL_ROOT=WARN
    volumes:
      - ./logs:/app/logs
      - ./lucene-index:/app/lucene
    networks:
      - product-api-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



networks:
  product-api-network:
    driver: bridge
    name: product-api-network

volumes:
