spring:
  application:
    name: modern-product-search

  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000

server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  # Enable CORS for hosted frontend
  forward-headers-strategy: framework

external:
  api:
    products:
      base-url: https://dummyjson.com
      endpoints:
        all-products: /products?limit=0
        product-by-id: /products/{id}
      timeout:
        connect: 10000
        read: 30000
      retry:
        max-attempts: 3
        delay: 2000

logging:
  level:
    com.productapi: INFO
    com.productapi.config.ProductionDataInitializer: DEBUG
    com.productapi.service.DataLoadService: DEBUG
    root: WARN

management:
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Resilience4j Configuration for External API calls
resilience4j:
  circuitbreaker:
    instances:
      external-api:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 60
        event-consumer-buffer-size: 10
  retry:
    instances:
      external-api:
        max-attempts: 5
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientResponseException
  timelimiter:
    instances:
      external-api:
        timeout-duration: 15s
