spring:
  application:
    name: modern-product-search

  datasource:
    url: jdbc:h2:mem:productdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 31536000
  mvc:
    static-path-pattern: /**

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  # Enable CORS for hosted frontend
  forward-headers-strategy: framework

external:
  api:
    base-url: https://dummyjson.com
    timeout:
      connect: 10000
      read: 30000

logging:
  level:
    com.productapi: INFO
    root: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
