# Docker-specific configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: product-orchestration-api
  
  # H2 Database Configuration for Docker
  datasource:
    url: jdbc:h2:mem:productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        # Hibernate Search Configuration for Docker
        search:
          backend:
            type: lucene
            directory:
              type: local-filesystem
              root: /app/lucene/indexes
          automatic_indexing:
            synchronization:
              strategy: sync

# External API Configuration
external:
  api:
    products:
      base-url: ${EXTERNAL_API_BASE_URL:https://dummyjson.com}
      endpoints:
        all-products: /products?limit=0
        product-by-id: /products/{id}
      timeout:
        connect: ${EXTERNAL_API_TIMEOUT_CONNECT:5000}
        read: ${EXTERNAL_API_TIMEOUT_READ:10000}
      retry:
        max-attempts: 3
        delay: 1000

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      external-api:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
  retry:
    instances:
      external-api:
        max-attempts: 3
        wait-duration: 1s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.reactive.function.client.WebClientRequestException
          - java.util.concurrent.TimeoutException
  timelimiter:
    instances:
      external-api:
        timeout-duration: 10s

# Logging Configuration for Docker
logging:
  level:
    com.productapi: ${LOGGING_LEVEL_COM_PRODUCTAPI:INFO}
    org.hibernate.search: WARN
    org.springframework.web.reactive.function.client: WARN
    root: ${LOGGING_LEVEL_ROOT:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/product-api.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 1GB

# Management and Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Application Info
info:
  app:
    name: Product Orchestration API
    description: RESTful API for loading and searching product data from external sources
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}

# OpenAPI Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
  info:
    title: Product Orchestration API
    description: RESTful API for loading and searching product data from external sources
    version: 1.0.0
    contact:
      name: Product API Team
      email: support@productapi.com
